import { createContext, useContext, useState, ReactNode } from "react";

type Language = "id" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  id: {
    // Navbar
    "nav.home": "Beranda",
    "nav.about": "Tentang",
    "nav.services": "Layanan",
    "nav.portfolio": "Portfolio",
    "nav.contact": "Kontak",
    "nav.cta": "Konsultasi Gratis",
    
    // Home Page
    "home.hero.title": "Jasa Pembuatan Website & Kursus Coding",
    "home.hero.subtitle": "Solusi profesional untuk pembuatan website dan pembelajaran teknologi.",
    "home.hero.cta1": "Pesan Sekarang",
    "home.hero.cta2": "Daftar Kursus",
    "home.hero.feat1": "100% Profesional",
    "home.hero.feat2": "Harga Terjangkau",
    "home.hero.feat3": "Support 24/7",
    
    "home.about.title": "Tentang Ondisia",
    "home.about.desc": "Ondisia adalah penyedia jasa digital terpercaya yang berfokus pada pembuatan website profesional, optimasi website, jasa pengerjaan tugas, serta kursus pembuatan website dari dasar hingga mahir.",
    "home.about.item1": "Pembuatan Website",
    "home.about.item1Desc": "Website profesional dan modern",
    "home.about.item2": "Optimasi Website",
    "home.about.item2Desc": "Meningkatkan performa website",
    "home.about.item3": "Jasa Pengerjaan Tugas",
    "home.about.item3Desc": "Bantu mengerjakan tugas website",
    "home.about.item4": "Kursus Website",
    "home.about.item4Desc": "Belajar dari dasar hingga mahir",

    "home.services.title": "Layanan Kami",
    "home.services.subtitle": "Solusi lengkap untuk kebutuhan website dan pembelajaran coding Anda",
    "home.services.task.title": "Pengerjaan Tugas Website",
    "home.services.task.desc": "Bantu mengerjakan tugas website untuk sekolah dan kuliah dengan hasil yang memuaskan.",
    "home.services.task.feat1": "Tepat waktu",
    "home.services.task.feat2": "Kualitas terbaik",
    "home.services.task.feat3": "Dokumen lengkap",
    "home.services.opt.title": "Optimasi Website",
    "home.services.opt.desc": "Meningkatkan performa website Anda untuk loading yang lebih cepat dan SEO friendly.",
    "home.services.opt.feat1": "Optimasi kecepatan",
    "home.services.opt.feat2": "SEO optimization",
    "home.services.opt.feat3": "Mobile friendly",
    "home.services.dev.title": "Pembuatan Website dari Nol",
    "home.services.dev.desc": "Jasa pembuatan website profesional sesuai kebutuhan bisnis atau personal Anda.",
    "home.services.dev.feat1": "Desain modern",
    "home.services.dev.feat2": "Responsive design",
    "home.services.dev.feat3": "Maintenance support",
    "home.services.course.title": "Kursus Website",
    "home.services.course.desc": "Belajar membuat website dari dasar dengan HTML, CSS, dan JavaScript.",
    "home.services.course.feat1": "Materi lengkap",
    "home.services.course.feat2": "Praktik langsung",
    "home.services.course.feat3": "Sertifikat",

    "home.why.title": "Mengapa Memilih Kami",
    "home.why.subtitle": "Keunggulan yang membuat Ondisia menjadi pilihan terbaik untuk kebutuhan website Anda",
    "home.why.item1.title": "Cepat, Rapi, dan Profesional",
    "home.why.item1.desc": "Pengerjaan tepat waktu dengan hasil yang rapi dan profesional sesuai standar industri.",
    "home.why.item2.title": "Cocok untuk Tugas Sekolah/Kuliah",
    "home.why.item2.desc": "Pengalaman membantu berbagai tugas website dari tingkat sekolah hingga perguruan tinggi.",
    "home.why.item3.title": "Konsultasi Gratis",
    "home.why.item3.desc": "Konsultasi gratis untuk membantu menentukan solusi terbaik untuk kebutuhan Anda.",
    "home.why.item4.title": "Transparansi Harga",
    "home.why.item4.desc": "Harga yang kompetitif dan transparan tanpa biaya tersembunyi.",
    "home.why.item5.title": "Kursus Ramah Pemula",
    "home.why.item5.desc": "Materi kursus dirancang khusus untuk pemula dengan pendekatan yang mudah dipahami.",
    "home.why.item6.title": "Waktu Fleksibel",
    "home.why.item6.desc": "Jadwal yang fleksibel untuk kursus dan pengerjaan proyek sesuai waktu Anda.",
    
    // About Page
    "about.title": "Tentang Ondisia",
    "about.subtitle": "Kami adalah tim profesional yang berdedikasi untuk menciptakan solusi digital berkualitas tinggi untuk bisnis Anda",
    "about.story.title": "Cerita Kami",
    "about.story.p1": "Ondisia didirikan dengan visi untuk membantu bisnis Indonesia bertransformasi secara digital. Kami percaya bahwa setiap bisnis, baik besar maupun kecil, berhak mendapatkan solusi teknologi terbaik.",
    "about.story.p2": "Dengan tim yang terdiri dari developer, designer, dan konsultan berpengalaman, kami telah membantu ratusan klien mewujudkan visi digital mereka.",
    "about.story.p3": "Kami tidak hanya membuat website atau aplikasi - kami membangun solusi yang memberikan nilai nyata untuk bisnis Anda.",
    "about.values.title": "Nilai Kami",
    "about.values.subtitle": "Prinsip yang memandu setiap project yang kami kerjakan",
    "about.values.mission": "Misi Kami",
    "about.values.missionDesc": "Memberikan solusi digital terbaik yang membantu bisnis berkembang dan mencapai target mereka.",
    "about.values.vision": "Visi Kami",
    "about.values.visionDesc": "Menjadi partner teknologi terpercaya untuk transformasi digital di Indonesia.",
    "about.values.commitment": "Komitmen Kami",
    "about.values.commitmentDesc": "Kualitas tinggi, komunikasi transparan, dan kepuasan klien adalah prioritas utama.",
    "about.why.title": "Mengapa Memilih Kami?",
    "about.why.experience": "Tahun Pengalaman",
    "about.why.team": "Tim Expert",
    "about.why.support": "Support",
    "about.why.satisfaction": "Satisfaction",
    
    // Services Page
    "services.title": "Layanan Kami",
    "services.subtitle": "Solusi digital lengkap untuk membantu bisnis Anda berkembang dan mencapai kesuksesan",
    "services.web.title": "Web Development",
    "services.web.desc": "Pembuatan website profesional dengan teknologi terkini seperti React, Vue.js, dan Next.js",
    "services.mobile.title": "Mobile App Development",
    "services.mobile.desc": "Aplikasi mobile native dan cross-platform untuk iOS and Android",
    "services.design.title": "UI/UX Design",
    "services.design.desc": "Desain interface yang menarik, modern, dan user-friendly",
    "services.backend.title": "Backend Development",
    "services.backend.desc": "Sistem backend yang robust, scalable, dan aman",
    "services.cloud.title": "Cloud Solutions",
    "services.cloud.desc": "Deployment dan management aplikasi di cloud platform",
    "services.maintenance.title": "Maintenance & Support",
    "services.maintenance.desc": "Layanan maintenance dan support untuk aplikasi Anda",
    "services.seo.title": "SEO Optimization",
    "services.seo.desc": "Optimasi website untuk mesin pencari dan performa terbaik",
    "services.consulting.title": "Konsultasi IT",
    "services.consulting.desc": "Konsultasi dan strategi teknologi untuk bisnis Anda",
    
    "services.web.feat1": "Website Company Profile",
    "services.web.feat2": "E-Commerce Platform",
    "services.web.feat3": "Web Application",
    "services.web.feat4": "Landing Page",
    "services.mobile.feat1": "Android App Development",
    "services.mobile.feat2": "iOS App Development",
    "services.mobile.feat3": "React Native",
    "services.mobile.feat4": "Flutter Development",
    "services.design.feat1": "User Interface Design",
    "services.design.feat2": "User Experience Design",
    "services.design.feat3": "Prototyping",
    "services.design.feat4": "Brand Identity",
    "services.backend.feat1": "API Development",
    "services.backend.feat2": "Database Design",
    "services.backend.feat3": "Server Configuration",
    "services.backend.feat4": "Integration Services",
    "services.cloud.feat1": "AWS Services",
    "services.cloud.feat2": "Google Cloud",
    "services.cloud.feat3": "Azure Platform",
    "services.cloud.feat4": "DevOps Setup",
    "services.maintenance.feat1": "Bug Fixes",
    "services.maintenance.feat2": "Performance Optimization",
    "services.maintenance.feat3": "Security Updates",
    "services.maintenance.feat4": "Technical Support",
    "services.seo.feat1": "On-Page SEO",
    "services.seo.feat2": "Technical SEO",
    "services.seo.feat3": "Content Strategy",
    "services.seo.feat4": "Analytics Setup",
    "services.consulting.feat1": "Technology Audit",
    "services.consulting.feat2": "Solution Architecture",
    "services.consulting.feat3": "Project Planning",
    "services.consulting.feat4": "Best Practices",

    "services.process.title": "Proses Kerja Kami",
    "services.process.subtitle": "Metodologi yang terstruktur untuk hasil yang optimal",
    "services.process.step1": "Konsultasi",
    "services.process.step1Desc": "Diskusi kebutuhan dan scope project",
    "services.process.step2": "Planning",
    "services.process.step2Desc": "Perencanaan detail dan timeline",
    "services.process.step3": "Development",
    "services.process.step3Desc": "Pengembangan dan testing",
    "services.process.step4": "Launch",
    "services.process.step4Desc": "Deployment dan handover",
    "services.cta.title": "Siap Memulai Project Anda?",
    "services.cta.subtitle": "Konsultasikan kebutuhan digital Anda dengan tim expert kami",
    "services.cta.button": "Konsultasi Gratis",
    
    // Contact Page
    "contact.title": "Hubungi Kami",
    "contact.subtitle": "Mari diskusikan project Anda dan bagaimana kami bisa membantu",
    "contact.info.title": "Informasi Kontak",
    "contact.info.subtitle": "Jangan ragu untuk menghubungi kami. Tim kami siap membantu menjawab pertanyaan dan memberikan konsultasi gratis untuk project Anda.",
    "contact.info.email": "Email",
    "contact.info.phone": "Telepon",
    "contact.info.address": "Alamat",
    "contact.hours.title": "Jam Operasional",
    "contact.hours.weekday": "Senin - Jumat",
    "contact.hours.saturday": "Sabtu",
    "contact.hours.sunday": "Minggu",
    "contact.hours.closed": "Tutup",
    "contact.form.title": "Kirim Pesan",
    "contact.form.name": "Nama Lengkap",
    "contact.form.email": "Email",
    "contact.form.phone": "Nomor Telepon",
    "contact.form.service": "Layanan yang Diminati",
    "contact.form.servicePlaceholder": "Contoh: Web Development, Mobile App, dll",
    "contact.form.message": "Pesan",
    "contact.form.messagePlaceholder": "Ceritakan tentang project Anda...",
    "contact.form.submit": "Kirim Pesan",
    "contact.form.success": "Terima kasih! Kami akan segera menghubungi Anda.",
    
    // Portfolio Page
    "portfolio.title": "Portfolio Kami",
    "portfolio.subtitle": "Lihat berbagai project yang telah kami selesaikan dengan hasil yang membanggakan",
    "portfolio.filter.all": "Semua",
    "portfolio.filter.web": "Web Development",
    "portfolio.filter.mobile": "Mobile App",
    "portfolio.cta.title": "Tertarik dengan Project Kami?",
    "portfolio.cta.subtitle": "Mari diskusikan bagaimana kami bisa membantu mewujudkan project Anda",
    
    "portfolio.project1.title": "E-Commerce Platform",
    "portfolio.project1.desc": "Platform e-commerce lengkap dengan sistem payment gateway dan inventory management",
    "portfolio.project2.title": "Corporate Website",
    "portfolio.project2.desc": "Website corporate profesional dengan CMS untuk management konten",
    "portfolio.project3.title": "Mobile Banking App",
    "portfolio.project3.desc": "Aplikasi mobile banking dengan fitur transfer, pembayaran, dan investment",
    "portfolio.project4.title": "Learning Management System",
    "portfolio.project4.desc": "Platform pembelajaran online dengan video streaming dan quiz interaktif",
    "portfolio.project5.title": "Food Delivery App",
    "portfolio.project5.desc": "Aplikasi delivery makanan dengan real-time tracking dan payment integration",
    "portfolio.project6.title": "Healthcare Portal",
    "portfolio.project6.desc": "Portal kesehatan dengan fitur booking dokter dan telemedicine",
    "portfolio.project7.title": "Real Estate App",
    "portfolio.project7.desc": "Platform pencarian properti dengan fitur filter canggih dan peta interaktif",
    "portfolio.project8.title": "Fitness Tracker",
    "portfolio.project8.desc": "Aplikasi pelacak kebugaran dengan monitoring detak jantung dan target harian",
    "portfolio.project9.title": "SaaS Analytics Dashboard",
    "portfolio.project9.desc": "Dashboard analitik untuk bisnis dengan visualisasi data yang kompleks",
    "portfolio.project10.title": "Travel Booking System",
    "portfolio.project10.desc": "Sistem pemesanan perjalanan lengkap untuk tiket pesawat dan hotel",
    "portfolio.project11.title": "Smart Home App",
    "portfolio.project11.desc": "Aplikasi kontrol rumah pintar dengan integrasi IoT",
    "portfolio.project12.title": "Logistics Tracking",
    "portfolio.project12.desc": "Sistem pelacakan logistik real-time untuk manajemen armada",
    
    // Portfolio Detail
    "detail.overview": "Overview",
    "detail.features": "Fitur Utama",
    "detail.challenges": "Tantangan",
    "detail.results": "Hasil",
    "detail.related": "Portfolio Sejenis",
    "detail.viewMore": "Lihat Portfolio Lainnya",
    "detail.backToPortfolio": "Kembali ke Portfolio",
    "detail.cta.title": "Tertarik dengan Project Serupa?",
    "detail.cta.subtitle": "Mari diskusikan kebutuhan project Anda dengan tim kami",
    "detail.notFound": "Project tidak ditemukan",
    "detail.client": "Klien",
    "detail.duration": "Durasi",
    
    // Footer
    "footer.nav": "Navigasi",
    "footer.services": "Layanan",
    "footer.contact": "Kontak",

    // Common
    "common.loading": "Memuat...",
    "common.previous": "Sebelumnya",
    "common.next": "Selanjutnya",
    "404.title": "Wah, Halaman Tidak Ditemukan",
    "404.subtitle": "Sepertinya halaman yang Anda cari tidak ada atau telah dipindahkan.",
    "404.link": "Kembali ke Beranda",
  },
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.contact": "Contact",
    "nav.cta": "Free Consultation",
    
    // Home Page
    "home.hero.title": "Website Creation & Coding Courses",
    "home.hero.subtitle": "Professional solutions for website development and technology learning.",
    "home.hero.cta1": "Order Now",
    "home.hero.cta2": "Join Course",
    "home.hero.feat1": "100% Professional",
    "home.hero.feat2": "Affordable Price",
    "home.hero.feat3": "24/7 Support",
    
    "home.about.title": "About Ondisia",
    "home.about.desc": "Ondisia is a trusted digital service provider focusing on professional website creation, website optimization, task assistance, and website development courses from basic to advanced.",
    "home.about.item1": "Website Creation",
    "home.about.item1Desc": "Professional and modern websites",
    "home.about.item2": "Website Optimization",
    "home.about.item2Desc": "Improving website performance",
    "home.about.item3": "Task Assistance",
    "home.about.item3Desc": "Help with website tasks",
    "home.about.item4": "Website Courses",
    "home.about.item4Desc": "Learn from basic to advanced",

    "home.services.title": "Our Services",
    "home.services.subtitle": "Complete solutions for your website and coding learning needs",
    "home.services.task.title": "Website Task Assistance",
    "home.services.task.desc": "Helping with website tasks for school and college with satisfying results.",
    "home.services.task.feat1": "On time",
    "home.services.task.feat2": "Best quality",
    "home.services.task.feat3": "Complete documents",
    "home.services.opt.title": "Website Optimization",
    "home.services.opt.desc": "Improving your website performance for faster loading and SEO friendliness.",
    "home.services.opt.feat1": "Speed optimization",
    "home.services.opt.feat2": "SEO optimization",
    "home.services.opt.feat3": "Mobile friendly",
    "home.services.dev.title": "Custom Website Development",
    "home.services.dev.desc": "Professional website development services according to your business or personal needs.",
    "home.services.dev.feat1": "Modern design",
    "home.services.dev.feat2": "Responsive design",
    "home.services.dev.feat3": "Maintenance support",
    "home.services.course.title": "Website Courses",
    "home.services.course.desc": "Learn to build websites from scratch with HTML, CSS, and JavaScript.",
    "home.services.course.feat1": "Complete material",
    "home.services.course.feat2": "Hands-on practice",
    "home.services.course.feat3": "Certificate",

    "home.why.title": "Why Choose Us",
    "home.why.subtitle": "Advantages that make Ondisia the best choice for your website needs",
    "home.why.item1.title": "Fast, Neat, and Professional",
    "home.why.item1.desc": "On-time delivery with neat and professional results according to industry standards.",
    "home.why.item2.title": "Perfect for School/College Tasks",
    "home.why.item2.desc": "Experience in helping with various website tasks from school to university levels.",
    "home.why.item3.title": "Free Consultation",
    "home.why.item3.desc": "Free consultation to help determine the best solution for your needs.",
    "home.why.item4.title": "Price Transparency",
    "home.why.item4.desc": "Competitive and transparent pricing with no hidden costs.",
    "home.why.item5.title": "Beginner-Friendly Courses",
    "home.why.item5.desc": "Course material specifically designed for beginners with an easy-to-understand approach.",
    "home.why.item6.title": "Flexible Time",
    "home.why.item6.desc": "Flexible schedules for courses and project execution according to your time.",
    
    // About Page
    "about.title": "About Ondisia",
    "about.subtitle": "We are a professional team dedicated to creating high-quality digital solutions for your business",
    "about.story.title": "Our Story",
    "about.story.p1": "Ondisia was founded with the vision to help Indonesian businesses transform digitally. We believe that every business, large or small, deserves the best technology solutions.",
    "about.story.p2": "With a team of experienced developers, designers, and consultants, we have helped hundreds of clients realize their digital vision.",
    "about.story.p3": "We don't just build websites or apps - we build solutions that provide real value to your business.",
    "about.values.title": "Our Values",
    "about.values.subtitle": "Principles that guide every project we work on",
    "about.values.mission": "Our Mission",
    "about.values.missionDesc": "Provide the best digital solutions that help businesses grow and achieve their goals.",
    "about.values.vision": "Our Vision",
    "about.values.visionDesc": "To be a trusted technology partner for digital transformation in Indonesia.",
    "about.values.commitment": "Our Commitment",
    "about.values.commitmentDesc": "High quality, transparent communication, and client satisfaction are our top priorities.",
    "about.why.title": "Why Choose Us?",
    "about.why.experience": "Years of Experience",
    "about.why.team": "Expert Team",
    "about.why.support": "Support",
    "about.why.satisfaction": "Satisfaction",
    
    // Services Page
    "services.title": "Our Services",
    "services.subtitle": "Complete digital solutions to help your business grow and achieve success",
    "services.web.title": "Web Development",
    "services.web.desc": "Professional website development with cutting-edge technologies like React, Vue.js, and Next.js",
    "services.mobile.title": "Mobile App Development",
    "services.mobile.desc": "Native and cross-platform mobile applications for iOS and Android",
    "services.design.title": "UI/UX Design",
    "services.design.desc": "Attractive, modern, and user-friendly interface design",
    "services.backend.title": "Backend Development",
    "services.backend.desc": "Robust, scalable, and secure backend systems",
    "services.cloud.title": "Cloud Solutions",
    "services.cloud.desc": "Application deployment and management on cloud platforms",
    "services.maintenance.title": "Maintenance & Support",
    "services.maintenance.desc": "Maintenance and support services for your applications",
    "services.seo.title": "SEO Optimization",
    "services.seo.desc": "Website optimization for search engines and best performance",
    "services.consulting.title": "IT Consulting",
    "services.consulting.desc": "Technology consultation and strategy for your business",
    
    "services.web.feat1": "Website Company Profile",
    "services.web.feat2": "E-Commerce Platform",
    "services.web.feat3": "Web Application",
    "services.web.feat4": "Landing Page",
    "services.mobile.feat1": "Android App Development",
    "services.mobile.feat2": "iOS App Development",
    "services.mobile.feat3": "React Native",
    "services.mobile.feat4": "Flutter Development",
    "services.design.feat1": "User Interface Design",
    "services.design.feat2": "User Experience Design",
    "services.design.feat3": "Prototyping",
    "services.design.feat4": "Brand Identity",
    "services.backend.feat1": "API Development",
    "services.backend.feat2": "Database Design",
    "services.backend.feat3": "Server Configuration",
    "services.backend.feat4": "Integration Services",
    "services.cloud.feat1": "AWS Services",
    "services.cloud.feat2": "Google Cloud",
    "services.cloud.feat3": "Azure Platform",
    "services.cloud.feat4": "DevOps Setup",
    "services.maintenance.feat1": "Bug Fixes",
    "services.maintenance.feat2": "Performance Optimization",
    "services.maintenance.feat3": "Security Updates",
    "services.maintenance.feat4": "Technical Support",
    "services.seo.feat1": "On-Page SEO",
    "services.seo.feat2": "Technical SEO",
    "services.seo.feat3": "Content Strategy",
    "services.seo.feat4": "Analytics Setup",
    "services.consulting.feat1": "Technology Audit",
    "services.consulting.feat2": "Solution Architecture",
    "services.consulting.feat3": "Project Planning",
    "services.consulting.feat4": "Best Practices",
    "services.process.title": "Our Work Process",
    "services.process.subtitle": "Structured methodology for optimal results",
    "services.process.step1": "Consultation",
    "services.process.step1Desc": "Discuss needs and project scope",
    "services.process.step2": "Planning",
    "services.process.step2Desc": "Detailed planning and timeline",
    "services.process.step3": "Development",
    "services.process.step3Desc": "Development and testing",
    "services.process.step4": "Launch",
    "services.process.step4Desc": "Deployment and handover",
    "services.cta.title": "Ready to Start Your Project?",
    "services.cta.subtitle": "Consult your digital needs with our expert team",
    "services.cta.button": "Free Consultation",
    
    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "Let's discuss your project and how we can help",
    "contact.info.title": "Contact Information",
    "contact.info.subtitle": "Don't hesitate to contact us. Our team is ready to help answer questions and provide free consultation for your project.",
    "contact.info.email": "Email",
    "contact.info.phone": "Phone",
    "contact.info.address": "Address",
    "contact.hours.title": "Office Hours",
    "contact.hours.weekday": "Monday - Friday",
    "contact.hours.saturday": "Saturday",
    "contact.hours.sunday": "Sunday",
    "contact.hours.closed": "Closed",
    "contact.form.title": "Send Message",
    "contact.form.name": "Full Name",
    "contact.form.email": "Email",
    "contact.form.phone": "Phone Number",
    "contact.form.service": "Service of Interest",
    "contact.form.servicePlaceholder": "Example: Web Development, Mobile App, etc",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Tell us about your project...",
    "contact.form.submit": "Send Message",
    "contact.form.success": "Thank you! We will contact you soon.",
    
    // Portfolio Page
    "portfolio.title": "Our Portfolio",
    "portfolio.subtitle": "Explore our completed projects with outstanding results",
    "portfolio.filter.all": "All",
    "portfolio.filter.web": "Web Development",
    "portfolio.filter.mobile": "Mobile App",
    "portfolio.cta.title": "Interested in Our Projects?",
    "portfolio.cta.subtitle": "Let's discuss how we can help bring your project to life",
    
    "portfolio.project1.title": "E-Commerce Platform",
    "portfolio.project1.desc": "Complete e-commerce platform with payment gateway and inventory management system",
    "portfolio.project2.title": "Corporate Website",
    "portfolio.project2.desc": "Professional corporate website with CMS for content management",
    "portfolio.project3.title": "Mobile Banking App",
    "portfolio.project3.desc": "Mobile banking application with transfer, payment, and investment features",
    "portfolio.project4.title": "Learning Management System",
    "portfolio.project4.desc": "Online learning platform with video streaming and interactive quizzes",
    "portfolio.project5.title": "Food Delivery App",
    "portfolio.project5.desc": "Food delivery application with real-time tracking and payment integration",
    "portfolio.project6.title": "Healthcare Portal",
    "portfolio.project6.desc": "Healthcare portal with doctor booking and telemedicine features",
    "portfolio.project7.title": "Real Estate App",
    "portfolio.project7.desc": "Property search platform with advanced filtering and interactive maps",
    "portfolio.project8.title": "Fitness Tracker",
    "portfolio.project8.desc": "Fitness tracking app with heart rate monitoring and daily goals",
    "portfolio.project9.title": "SaaS Analytics Dashboard",
    "portfolio.project9.desc": "Business analytics dashboard with complex data visualizations",
    "portfolio.project10.title": "Travel Booking System",
    "portfolio.project10.desc": "Complete travel booking system for flights and hotels",
    "portfolio.project11.title": "Smart Home App",
    "portfolio.project11.desc": "Smart home control application with IoT integration",
    "portfolio.project12.title": "Logistics Tracking",
    "portfolio.project12.desc": "Real-time logistics tracking system for fleet management",
    
    // Portfolio Detail
    "detail.overview": "Overview",
    "detail.features": "Key Features",
    "detail.challenges": "Challenges",
    "detail.results": "Results",
    "detail.related": "Related Projects",
    "detail.viewMore": "View All Portfolio",
    "detail.backToPortfolio": "Back to Portfolio",
    "detail.cta.title": "Interested in Similar Projects?",
    "detail.cta.subtitle": "Let's discuss your project needs with our team",
    "detail.notFound": "Project not found",
    "detail.client": "Client",
    "detail.duration": "Duration",

    // Footer
    "footer.nav": "Navigation",
    "footer.services": "Services",
    "footer.contact": "Contact",
    
    // Common
    "common.loading": "Loading...",
    "common.previous": "Previous",
    "common.next": "Next",
    "404.title": "Oops! Page Not Found",
    "404.subtitle": "The page you are looking for doesn't exist or has been moved.",
    "404.link": "Return to Home",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("id");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.id] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
