import { createContext, useContext, useState, ReactNode } from "react";

type Language = "id" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  id: {
    // Navbar
    "nav.home": "Beranda",
    "nav.about": "Tentang",
    "nav.services": "Layanan",
    "nav.portfolio": "Portfolio",
    "nav.contact": "Kontak",
    "nav.apps": "Produk Kami",
    "nav.cta": "Konsultasi Gratis",
    
    // Home Page
    "home.hero.title": "Jasa Pembuatan Website & Kursus Coding",
    "home.hero.subtitle": "Solusi profesional untuk pembuatan website dan pembelajaran teknologi.",
    "home.hero.cta1": "Pesan Sekarang",
    "home.hero.cta2": "Daftar Layanan",
    "home.hero.feat1": "100% Profesional",
    "home.hero.feat2": "Harga Terjangkau",
    "home.hero.feat3": "Support 24/7",
    
    "home.apps.title": "Ekosistem Ondisia",
    "home.apps.subtitle": "Produk dan aplikasi inovatif yang kami kembangkan untuk berbagai kebutuhan.",
    "apps.store.title": "Ondistore",
    "apps.store.desc": "Platform marketplace untuk berbagai produk digital dan layanan kami.",
    "apps.store.status": "Live",
    "apps.card.title": "Ondicard",
    "apps.card.desc": "Platform pembuatan undangan digital yang modern dan interaktif.",
    "apps.card.status": "Dalam Pengembangan",
    "apps.pes.title": "Ondipes",
    "apps.pes.desc": "Sistem Informasi Manajemen Pesantren yang terintegrasi penuh.",
    "apps.pes.status": "Dalam Pengembangan",

    "home.about.title": "Tentang Ondisia",
    "home.about.desc": "Ondisia adalah penyedia jasa digital terpercaya yang berfokus pada pembuatan website profesional, optimasi website, jasa pengerjaan tugas, serta kursus pembuatan website dari dasar hingga mahir.",
    "home.about.item1": "Pembuatan Website",
    "home.about.item1Desc": "Website profesional dan modern",
    "home.about.item2": "Optimasi Website",
    "home.about.item2Desc": "Meningkatkan performa website",
    "home.about.item3": "Konsultasi Teknologi",
    "home.about.item3Desc": "Solusi & strategi digital bisnis",
    "home.about.item4": "Kursus Website",
    "home.about.item4Desc": "Belajar dari dasar hingga mahir",

    "home.services.title": "Layanan Kami",
    "home.services.subtitle": "Solusi lengkap untuk kebutuhan website dan pembelajaran coding Anda",
    "home.services.task.title": "Konsultasi Teknologi & IT",
    "home.services.task.desc": "Konsultasi strategis untuk transformasi digital bisnis Anda, mulai dari arsitektur sistem hingga pemilihan teknologi yang tepat.",
    "home.services.task.feat1": "Audit sistem & teknologi",
    "home.services.task.feat2": "Strategi transformasi digital",
    "home.services.task.feat3": "Roadmap pengembangan",
    "home.services.opt.title": "Optimasi Website",
    "home.services.opt.desc": "Meningkatkan performa website Anda untuk loading yang lebih cepat dan SEO friendly.",
    "home.services.opt.feat1": "Optimasi kecepatan",
    "home.services.opt.feat2": "SEO optimization",
    "home.services.opt.feat3": "Mobile friendly",
    "home.services.dev.title": "Pembuatan Website dari Nol",
    "home.services.dev.desc": "Jasa pembuatan website profesional sesuai kebutuhan bisnis atau personal Anda.",
    "home.services.dev.feat1": "Desain modern",
    "home.services.dev.feat2": "Responsive design",
    "home.services.dev.feat3": "Maintenance support",
    "home.services.course.title": "Kursus Website",
    "home.services.course.desc": "Belajar membuat website dari dasar dengan HTML, CSS, dan JavaScript.",
    "home.services.course.feat1": "Materi lengkap",
    "home.services.course.feat2": "Praktik langsung",
    "home.services.course.feat3": "Sertifikat",

    "home.why.title": "Mengapa Memilih Kami",
    "home.why.subtitle": "Keunggulan yang membuat Ondisia menjadi pilihan terbaik untuk kebutuhan website Anda",
    "home.why.item1.title": "Cepat, Rapi, dan Profesional",
    "home.why.item1.desc": "Pengerjaan tepat waktu dengan hasil yang rapi dan profesional sesuai standar industri.",
    "home.why.item2.title": "Solusi Bisnis Terarah",
    "home.why.item2.desc": "Pengalaman membantu berbagai jenis bisnis menemukan solusi teknologi yang tepat dan efisien.",
    "home.why.item3.title": "Konsultasi Gratis",
    "home.why.item3.desc": "Konsultasi gratis untuk membantu menentukan solusi terbaik untuk kebutuhan Anda.",
    "home.why.item4.title": "Transparansi Harga",
    "home.why.item4.desc": "Harga yang kompetitif dan transparan tanpa biaya tersembunyi.",
    "home.why.item5.title": "Kursus Ramah Pemula",
    "home.why.item5.desc": "Materi kursus dirancang khusus untuk pemula dengan pendekatan yang mudah dipahami.",
    "home.why.item6.title": "Waktu Fleksibel",
    "home.why.item6.desc": "Jadwal yang fleksibel untuk kursus dan pengerjaan proyek sesuai waktu Anda.",
    
    // About Page
    "about.title": "Tentang Ondisia",
    "about.subtitle": "Kami adalah tim profesional yang berdedikasi untuk menciptakan solusi digital berkualitas tinggi untuk bisnis Anda",
    "about.story.title": "Cerita Kami",
    "about.story.p1": "Ondisia didirikan dengan visi untuk membantu bisnis Indonesia bertransformasi secara digital. Kami percaya bahwa setiap bisnis, baik besar maupun kecil, berhak mendapatkan solusi teknologi terbaik.",
    "about.story.p2": "Dengan tim yang terdiri dari developer, designer, dan konsultan berpengalaman, kami telah membantu ratusan klien mewujudkan visi digital mereka.",
    "about.story.p3": "Kami tidak hanya membuat website atau aplikasi - kami membangun solusi yang memberikan nilai nyata untuk bisnis Anda.",
    "about.values.title": "Nilai Kami",
    "about.values.subtitle": "Prinsip yang memandu setiap project yang kami kerjakan",
    "about.values.mission": "Misi Kami",
    "about.values.missionDesc": "Memberikan solusi digital terbaik yang membantu bisnis berkembang dan mencapai target mereka.",
    "about.values.vision": "Visi Kami",
    "about.values.visionDesc": "Menjadi partner teknologi terpercaya untuk transformasi digital di Indonesia.",
    "about.values.commitment": "Komitmen Kami",
    "about.values.commitmentDesc": "Kualitas tinggi, komunikasi transparan, dan kepuasan klien adalah prioritas utama.",
    "about.why.title": "Mengapa Memilih Kami?",
    "about.why.experience": "Tahun Pengalaman",
    "about.why.team": "Tim Expert",
    "about.why.support": "Support",
    "about.why.satisfaction": "Satisfaction",
    
    // Services Page
    "services.title": "Layanan Kami",
    "services.subtitle": "Solusi digital lengkap untuk membantu bisnis Anda berkembang dan mencapai kesuksesan",
    "services.web.title": "Web Development",
    "services.web.desc": "Pembuatan website profesional dengan teknologi terkini seperti React, Vue.js, dan Next.js",
    "services.mobile.title": "Mobile App Development",
    "services.mobile.desc": "Aplikasi mobile native dan cross-platform untuk iOS and Android",
    "services.design.title": "UI/UX Design",
    "services.design.desc": "Desain interface yang menarik, modern, dan user-friendly",
    "services.backend.title": "Backend Development",
    "services.backend.desc": "Sistem backend yang robust, scalable, dan aman",
    "services.cloud.title": "Cloud Solutions",
    "services.cloud.desc": "Deployment dan management aplikasi di cloud platform",
    "services.maintenance.title": "Maintenance & Support",
    "services.maintenance.desc": "Layanan maintenance dan support untuk aplikasi Anda",
    "services.seo.title": "SEO Optimization",
    "services.seo.desc": "Optimasi website untuk mesin pencari dan performa terbaik",
    "services.consulting.title": "Konsultasi IT",
    "services.consulting.desc": "Konsultasi dan strategi teknologi untuk bisnis Anda",
    
    "services.web.feat1": "Website Company Profile",
    "services.web.feat2": "E-Commerce Platform",
    "services.web.feat3": "Web Application",
    "services.web.feat4": "Landing Page",
    "services.mobile.feat1": "Android App Development",
    "services.mobile.feat2": "iOS App Development",
    "services.mobile.feat3": "React Native",
    "services.mobile.feat4": "Flutter Development",
    "services.design.feat1": "User Interface Design",
    "services.design.feat2": "User Experience Design",
    "services.design.feat3": "Prototyping",
    "services.design.feat4": "Brand Identity",
    "services.backend.feat1": "API Development",
    "services.backend.feat2": "Database Design",
    "services.backend.feat3": "Server Configuration",
    "services.backend.feat4": "Integration Services",
    "services.cloud.feat1": "AWS Services",
    "services.cloud.feat2": "Google Cloud",
    "services.cloud.feat3": "Azure Platform",
    "services.cloud.feat4": "DevOps Setup",
    "services.maintenance.feat1": "Bug Fixes",
    "services.maintenance.feat2": "Performance Optimization",
    "services.maintenance.feat3": "Security Updates",
    "services.maintenance.feat4": "Technical Support",
    "services.seo.feat1": "On-Page SEO",
    "services.seo.feat2": "Technical SEO",
    "services.seo.feat3": "Content Strategy",
    "services.seo.feat4": "Analytics Setup",
    "services.consulting.feat1": "Technology Audit",
    "services.consulting.feat2": "Solution Architecture",
    "services.consulting.feat3": "Project Planning",
    "services.consulting.feat4": "Best Practices",

    "services.process.title": "Proses Kerja Kami",
    "services.process.subtitle": "Metodologi yang terstruktur untuk hasil yang optimal",
    "services.process.step1": "Konsultasi",
    "services.process.step1Desc": "Diskusi kebutuhan dan scope project",
    "services.process.step2": "Planning",
    "services.process.step2Desc": "Perencanaan detail dan timeline",
    "services.process.step3": "Development",
    "services.process.step3Desc": "Pengembangan dan testing",
    "services.process.step4": "Launch",
    "services.process.step4Desc": "Deployment dan handover",
    "services.cta.title": "Siap Memulai Project Anda?",
    "services.cta.subtitle": "Konsultasikan kebutuhan digital Anda dengan tim expert kami",
    "services.cta.button": "Konsultasi Gratis",
    
    // Contact Page
    "contact.title": "Hubungi Kami",
    "contact.subtitle": "Mari diskusikan project Anda dan bagaimana kami bisa membantu",
    "contact.info.title": "Informasi Kontak",
    "contact.info.subtitle": "Jangan ragu untuk menghubungi kami. Tim kami siap membantu menjawab pertanyaan dan memberikan konsultasi gratis untuk project Anda.",
    "contact.info.email": "Email",
    "contact.info.phone": "Telepon",
    "contact.info.address": "Alamat",
    "contact.hours.title": "Jam Operasional",
    "contact.hours.weekday": "Senin - Jumat",
    "contact.hours.saturday": "Sabtu",
    "contact.hours.sunday": "Minggu",
    "contact.hours.closed": "Tutup",
    "contact.form.title": "Kirim Pesan",
    "contact.form.waNote": "Pesan Anda akan dikirim langsung melalui WhatsApp",
    "contact.form.name": "Nama Lengkap",
    "contact.form.email": "Email",
    "contact.form.phone": "Nomor Telepon",
    "contact.form.service": "Layanan yang Diminati",
    "contact.form.servicePlaceholder": "Pilih layanan...",
    "contact.form.message": "Pesan",
    "contact.form.messagePlaceholder": "Ceritakan tentang project Anda...",
    "contact.form.submit": "Kirim via WhatsApp",
    "contact.form.success": "Mengarahkan ke WhatsApp...",
    
    // Portfolio Page
    "portfolio.title": "Portfolio Kami",
    "portfolio.subtitle": "Lihat berbagai project yang telah kami selesaikan dengan hasil yang membanggakan",
    "portfolio.filter.all": "Semua",
    "portfolio.filter.web": "Web Development",
    "portfolio.filter.mobile": "Mobile App",
    "portfolio.cta.title": "Tertarik dengan Project Kami?",
    "portfolio.cta.subtitle": "Mari diskusikan bagaimana kami bisa membantu mewujudkan project Anda",
    
    "portfolio.project1.title": "StartFlow",
    "portfolio.project1.desc": "Platform akselerator startup untuk membantu pengembangan bisnis lebih cepat dan efisien.",
    "portfolio.project2.title": "UMK-M Mart",
    "portfolio.project2.desc": "Marketplace standar global yang dirancang khusus untuk memberdayakan pelaku UMKM.",
    "portfolio.project3.title": "Visit Nusantara",
    "portfolio.project3.desc": "Portal pariwisata komprehensif untuk mengeksplorasi keindahan destinasi wisata di Indonesia.",
    "portfolio.project4.title": "EduForm",
    "portfolio.project4.desc": "Platform edukasi modern untuk manajemen formulir dan data pendidikan secara online.",
    "portfolio.project5.title": "StartFlow PSI",
    "portfolio.project5.desc": "Solusi manajemen startup terintegrasi untuk optimasi performa dan skalabilitas bisnis.",
    "portfolio.project6.title": "BookEase",
    "portfolio.project6.desc": "Sistem pemesanan layanan yang memudahkan pelanggan dalam melakukan reservasi secara online.",
    "portfolio.project7.title": "EventInfo",
    "portfolio.project7.desc": "Aplikasi informasi event terkini yang memudahkan pengguna menemukan acara menarik di sekitar mereka.",
    "portfolio.project8.title": "BizTrack",
    "portfolio.project8.desc": "Aplikasi pelacakan bisnis untuk memonitor performa dan operasional usaha secara real-time.",
    "portfolio.project9.title": "UMKM Hub",
    "portfolio.project9.desc": "Pusat ekosistem digital untuk mendukung pertumbuhan dan kolaborasi antar pelaku UMKM.",
    "portfolio.project10.title": "Lapor Warga",
    "portfolio.project10.desc": "Aplikasi layanan pengaduan warga untuk mempercepat respon pemerintah terhadap masalah publik.",
    "portfolio.project11.title": "Course Lesson",
    "portfolio.project11.desc": "Aplikasi pembelajaran mobile yang menyediakan berbagai kursus interaktif untuk pengembangan diri.",
    "portfolio.project12.title": "SmartBooking",
    "portfolio.project12.desc": "Sistem reservasi pintar untuk pengelolaan kunjungan dan antrean yang lebih terorganisir.",
    
    // Portfolio Detail
    "detail.overview": "Overview",
    "detail.features": "Fitur Utama",
    "detail.challenges": "Tantangan",
    "detail.results": "Hasil",
    "detail.related": "Portfolio Sejenis",
    "detail.viewMore": "Lihat Portfolio Lainnya",
    "detail.backToPortfolio": "Kembali ke Portfolio",
    "detail.cta.title": "Tertarik dengan Project Serupa?",
    "detail.cta.subtitle": "Mari diskusikan kebutuhan project Anda dengan tim kami",
    "detail.notFound": "Project tidak ditemukan",
    "detail.client": "Klien",
    "detail.duration": "Durasi",
    
    // Testimonials
    "testimonials.title": "Apa Kata Klien Kami",
    "testimonials.subtitle": "Kepuasan klien adalah prioritas utama kami",
    "testimonials.1.name": "Rizky Firmansyah",
    "testimonials.1.role": "Founder, StartFlow",
    "testimonials.1.text": "Ondisia benar-benar mengubah cara pandang kami soal digital. Website yang dibuat sangat profesional dan pengerjaannya cepat. Sangat rekomendasikan!",
    "testimonials.2.name": "Siti Rahmawati",
    "testimonials.2.role": "Owner, UMKM Batik Nusantara",
    "testimonials.2.text": "Awalnya saya ragu, tapi hasilnya melebihi ekspektasi. Tim Ondisia sangat responsif dan sabar menjelaskan setiap prosesnya.",
    "testimonials.3.name": "Andi Prasetyo",
    "testimonials.3.role": "CTO, EduTech Solusindo",
    "testimonials.3.text": "Konsultasi IT dari Ondisia sangat membantu kami memilih stack teknologi yang tepat. Hasilnya sistem kami jauh lebih scalable sekarang.",

    // FAQ
    "faq.title": "Pertanyaan yang Sering Ditanyakan",
    "faq.subtitle": "Temukan jawaban untuk pertanyaan umum seputar layanan kami",
    "faq.q1": "Berapa lama waktu pengerjaan website?",
    "faq.a1": "Tergantung kompleksitas project. Landing page biasanya 3–7 hari, website company profile 1–2 minggu, dan aplikasi web/mobile 1–3 bulan.",
    "faq.q2": "Apakah ada garansi setelah project selesai?",
    "faq.a2": "Ya, kami memberikan garansi maintenance gratis selama 1 bulan setelah project selesai untuk perbaikan bug dan perubahan minor.",
    "faq.q3": "Teknologi apa yang digunakan?",
    "faq.a3": "Kami menggunakan teknologi terkini seperti React, Next.js, React Native, Node.js, dan berbagai cloud platform sesuai kebutuhan project.",
    "faq.q4": "Bagaimana sistem pembayaran?",
    "faq.a4": "Pembayaran dilakukan 50% di awal sebagai tanda jadi, dan 50% setelah project selesai dan disetujui klien.",
    "faq.q5": "Apakah bisa request revisi?",
    "faq.a5": "Tentu. Kami menyediakan 3x revisi gratis selama proses pengerjaan. Revisi tambahan dapat didiskusikan bersama.",

    // Footer
    "footer.nav": "Navigasi",
    "footer.services": "Layanan",
    "footer.contact": "Kontak",

    // Common
    "common.loading": "Memuat...",
    "common.previous": "Sebelumnya",
    "common.next": "Selanjutnya",
    "404.title": "Wah, Halaman Tidak Ditemukan",
    "404.subtitle": "Sepertinya halaman yang Anda cari tidak ada atau telah dipindahkan.",
    "404.link": "Kembali ke Beranda",
  },
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.contact": "Contact",
    "nav.apps": "Our Apps",
    "nav.cta": "Free Consultation",
    
    // Home Page
    "home.hero.title": "Website Creation & Coding Courses",
    "home.hero.subtitle": "Professional solutions for website development and technology learning.",
    "home.hero.cta1": "Order Now",
    "home.hero.cta2": "Our Services",
    "home.hero.feat1": "100% Professional",
    "home.hero.feat2": "Affordable Price",
    "home.hero.feat3": "24/7 Support",
    
    "home.apps.title": "Ondisia Ecosystem",
    "home.apps.subtitle": "Innovative products and applications we develop for various needs.",
    "apps.store.title": "Ondistore",
    "apps.store.desc": "Marketplace platform for our digital products and services.",
    "apps.store.status": "Live",
    "apps.card.title": "Ondicard",
    "apps.card.desc": "Modern and interactive digital invitation creation platform.",
    "apps.card.status": "In Development",
    "apps.pes.title": "Ondipes",
    "apps.pes.desc": "Integrated Islamic Boarding School Management Information System.",
    "apps.pes.status": "In Development",

    "home.about.title": "About Ondisia",
    "home.about.desc": "Ondisia is a trusted digital service provider focusing on professional website creation, website optimization, task assistance, and website development courses from basic to advanced.",
    "home.about.item1": "Website Creation",
    "home.about.item1Desc": "Professional and modern websites",
    "home.about.item2": "Website Optimization",
    "home.about.item2Desc": "Improving website performance",
    "home.about.item3": "Tech Consulting",
    "home.about.item3Desc": "Digital solutions & business strategy",
    "home.about.item4": "Website Courses",
    "home.about.item4Desc": "Learn from basic to advanced",

    "home.services.title": "Our Services",
    "home.services.subtitle": "Complete solutions for your website and coding learning needs",
    "home.services.task.title": "Technology & IT Consulting",
    "home.services.task.desc": "Strategic consulting for your business digital transformation, from system architecture to technology selection.",
    "home.services.task.feat1": "System & technology audit",
    "home.services.task.feat2": "Digital transformation strategy",
    "home.services.task.feat3": "Development roadmap",
    "home.services.opt.title": "Website Optimization",
    "home.services.opt.desc": "Improving your website performance for faster loading and SEO friendliness.",
    "home.services.opt.feat1": "Speed optimization",
    "home.services.opt.feat2": "SEO optimization",
    "home.services.opt.feat3": "Mobile friendly",
    "home.services.dev.title": "Custom Website Development",
    "home.services.dev.desc": "Professional website development services according to your business or personal needs.",
    "home.services.dev.feat1": "Modern design",
    "home.services.dev.feat2": "Responsive design",
    "home.services.dev.feat3": "Maintenance support",
    "home.services.course.title": "Website Courses",
    "home.services.course.desc": "Learn to build websites from scratch with HTML, CSS, and JavaScript.",
    "home.services.course.feat1": "Complete material",
    "home.services.course.feat2": "Hands-on practice",
    "home.services.course.feat3": "Certificate",

    "home.why.title": "Why Choose Us",
    "home.why.subtitle": "Advantages that make Ondisia the best choice for your website needs",
    "home.why.item1.title": "Fast, Neat, and Professional",
    "home.why.item1.desc": "On-time delivery with neat and professional results according to industry standards.",
    "home.why.item2.title": "Goal-Oriented Solutions",
    "home.why.item2.desc": "Experience helping various businesses find the right and efficient technology solutions.",
    "home.why.item3.title": "Free Consultation",
    "home.why.item3.desc": "Free consultation to help determine the best solution for your needs.",
    "home.why.item4.title": "Price Transparency",
    "home.why.item4.desc": "Competitive and transparent pricing with no hidden costs.",
    "home.why.item5.title": "Beginner-Friendly Courses",
    "home.why.item5.desc": "Course material specifically designed for beginners with an easy-to-understand approach.",
    "home.why.item6.title": "Flexible Time",
    "home.why.item6.desc": "Flexible schedules for courses and project execution according to your time.",
    
    // About Page
    "about.title": "About Ondisia",
    "about.subtitle": "We are a professional team dedicated to creating high-quality digital solutions for your business",
    "about.story.title": "Our Story",
    "about.story.p1": "Ondisia was founded with the vision to help Indonesian businesses transform digitally. We believe that every business, large or small, deserves the best technology solutions.",
    "about.story.p2": "With a team of experienced developers, designers, and consultants, we have helped hundreds of clients realize their digital vision.",
    "about.story.p3": "We don't just build websites or apps - we build solutions that provide real value to your business.",
    "about.values.title": "Our Values",
    "about.values.subtitle": "Principles that guide every project we work on",
    "about.values.mission": "Our Mission",
    "about.values.missionDesc": "Provide the best digital solutions that help businesses grow and achieve their goals.",
    "about.values.vision": "Our Vision",
    "about.values.visionDesc": "To be a trusted technology partner for digital transformation in Indonesia.",
    "about.values.commitment": "Our Commitment",
    "about.values.commitmentDesc": "High quality, transparent communication, and client satisfaction are our top priorities.",
    "about.why.title": "Why Choose Us?",
    "about.why.experience": "Years of Experience",
    "about.why.team": "Expert Team",
    "about.why.support": "Support",
    "about.why.satisfaction": "Satisfaction",
    
    // Services Page
    "services.title": "Our Services",
    "services.subtitle": "Complete digital solutions to help your business grow and achieve success",
    "services.web.title": "Web Development",
    "services.web.desc": "Professional website development with cutting-edge technologies like React, Vue.js, and Next.js",
    "services.mobile.title": "Mobile App Development",
    "services.mobile.desc": "Native and cross-platform mobile applications for iOS and Android",
    "services.design.title": "UI/UX Design",
    "services.design.desc": "Attractive, modern, and user-friendly interface design",
    "services.backend.title": "Backend Development",
    "services.backend.desc": "Robust, scalable, and secure backend systems",
    "services.cloud.title": "Cloud Solutions",
    "services.cloud.desc": "Application deployment and management on cloud platforms",
    "services.maintenance.title": "Maintenance & Support",
    "services.maintenance.desc": "Maintenance and support services for your applications",
    "services.seo.title": "SEO Optimization",
    "services.seo.desc": "Website optimization for search engines and best performance",
    "services.consulting.title": "IT Consulting",
    "services.consulting.desc": "Technology consultation and strategy for your business",
    
    "services.web.feat1": "Website Company Profile",
    "services.web.feat2": "E-Commerce Platform",
    "services.web.feat3": "Web Application",
    "services.web.feat4": "Landing Page",
    "services.mobile.feat1": "Android App Development",
    "services.mobile.feat2": "iOS App Development",
    "services.mobile.feat3": "React Native",
    "services.mobile.feat4": "Flutter Development",
    "services.design.feat1": "User Interface Design",
    "services.design.feat2": "User Experience Design",
    "services.design.feat3": "Prototyping",
    "services.design.feat4": "Brand Identity",
    "services.backend.feat1": "API Development",
    "services.backend.feat2": "Database Design",
    "services.backend.feat3": "Server Configuration",
    "services.backend.feat4": "Integration Services",
    "services.cloud.feat1": "AWS Services",
    "services.cloud.feat2": "Google Cloud",
    "services.cloud.feat3": "Azure Platform",
    "services.cloud.feat4": "DevOps Setup",
    "services.maintenance.feat1": "Bug Fixes",
    "services.maintenance.feat2": "Performance Optimization",
    "services.maintenance.feat3": "Security Updates",
    "services.maintenance.feat4": "Technical Support",
    "services.seo.feat1": "On-Page SEO",
    "services.seo.feat2": "Technical SEO",
    "services.seo.feat3": "Content Strategy",
    "services.seo.feat4": "Analytics Setup",
    "services.consulting.feat1": "Technology Audit",
    "services.consulting.feat2": "Solution Architecture",
    "services.consulting.feat3": "Project Planning",
    "services.consulting.feat4": "Best Practices",
    "services.process.title": "Our Work Process",
    "services.process.subtitle": "Structured methodology for optimal results",
    "services.process.step1": "Consultation",
    "services.process.step1Desc": "Discuss needs and project scope",
    "services.process.step2": "Planning",
    "services.process.step2Desc": "Detailed planning and timeline",
    "services.process.step3": "Development",
    "services.process.step3Desc": "Development and testing",
    "services.process.step4": "Launch",
    "services.process.step4Desc": "Deployment and handover",
    "services.cta.title": "Ready to Start Your Project?",
    "services.cta.subtitle": "Consult your digital needs with our expert team",
    "services.cta.button": "Free Consultation",
    
    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "Let's discuss your project and how we can help",
    "contact.info.title": "Contact Information",
    "contact.info.subtitle": "Don't hesitate to contact us. Our team is ready to help answer questions and provide free consultation for your project.",
    "contact.info.email": "Email",
    "contact.info.phone": "Phone",
    "contact.info.address": "Address",
    "contact.hours.title": "Office Hours",
    "contact.hours.weekday": "Monday - Friday",
    "contact.hours.saturday": "Saturday",
    "contact.hours.sunday": "Sunday",
    "contact.hours.closed": "Closed",
    "contact.form.title": "Send Message",
    "contact.form.waNote": "Your message will be sent directly via WhatsApp",
    "contact.form.name": "Full Name",
    "contact.form.email": "Email",
    "contact.form.phone": "Phone Number",
    "contact.form.service": "Service of Interest",
    "contact.form.servicePlaceholder": "Select a service...",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Tell us about your project...",
    "contact.form.submit": "Send via WhatsApp",
    "contact.form.success": "Redirecting to WhatsApp...",
    
    // Portfolio Page
    "portfolio.title": "Our Portfolio",
    "portfolio.subtitle": "Explore our completed projects with outstanding results",
    "portfolio.filter.all": "All",
    "portfolio.filter.web": "Web Development",
    "portfolio.filter.mobile": "Mobile App",
    "portfolio.cta.title": "Interested in Our Projects?",
    "portfolio.cta.subtitle": "Let's discuss how we can help bring your project to life",
    
    "portfolio.project1.title": "StartFlow",
    "portfolio.project1.desc": "Startup accelerator platform to help businesses grow faster and more efficiently.",
    "portfolio.project2.title": "UMK-M Mart",
    "portfolio.project2.desc": "Global standard marketplace specifically designed to empower MSME players.",
    "portfolio.project3.title": "Visit Nusantara",
    "portfolio.project3.desc": "Comprehensive tourism portal to explore the beauty of travel destinations in Indonesia.",
    "portfolio.project4.title": "EduForm",
    "portfolio.project4.desc": "Modern education platform for online form and educational data management.",
    "portfolio.project5.title": "StartFlow PSI",
    "portfolio.project5.desc": "Integrated startup management solution for business performance and scalability optimization.",
    "portfolio.project6.title": "BookEase",
    "portfolio.project6.desc": "Service booking system that makes it easy for customers to make online reservations.",
    "portfolio.project7.title": "EventInfo",
    "portfolio.project7.desc": "Latest event information application that helps users find interesting events near them.",
    "portfolio.project8.title": "BizTrack",
    "portfolio.project8.desc": "Business tracking application to monitor business performance and operations in real-time.",
    "portfolio.project9.title": "UMKM Hub",
    "portfolio.project9.desc": "Digital ecosystem center to support growth and collaboration between MSME players.",
    "portfolio.project10.title": "Lapor Warga",
    "portfolio.project10.desc": "Citizen reporting application to speed up government response to public issues.",
    "portfolio.project11.title": "Course Lesson",
    "portfolio.project11.desc": "Mobile learning application providing various interactive courses for self-development.",
    "portfolio.project12.title": "SmartBooking",
    "portfolio.project12.desc": "Smart reservation system for more organized visit and queue management.",
    
    // Portfolio Detail
    "detail.overview": "Overview",
    "detail.features": "Key Features",
    "detail.challenges": "Challenges",
    "detail.results": "Results",
    "detail.related": "Related Projects",
    "detail.viewMore": "View All Portfolio",
    "detail.backToPortfolio": "Back to Portfolio",
    "detail.cta.title": "Interested in Similar Projects?",
    "detail.cta.subtitle": "Let's discuss your project needs with our team",
    "detail.notFound": "Project not found",
    "detail.client": "Client",
    "detail.duration": "Duration",

    // Testimonials
    "testimonials.title": "What Our Clients Say",
    "testimonials.subtitle": "Client satisfaction is our top priority",
    "testimonials.1.name": "Rizky Firmansyah",
    "testimonials.1.role": "Founder, StartFlow",
    "testimonials.1.text": "Ondisia truly changed our perspective on digital. The website they built is very professional and delivered quickly. Highly recommended!",
    "testimonials.2.name": "Siti Rahmawati",
    "testimonials.2.role": "Owner, UMKM Batik Nusantara",
    "testimonials.2.text": "I was hesitant at first, but the result exceeded expectations. The Ondisia team is very responsive and patiently explains every step.",
    "testimonials.3.name": "Andi Prasetyo",
    "testimonials.3.role": "CTO, EduTech Solusindo",
    "testimonials.3.text": "The IT consulting from Ondisia helped us choose the right technology stack. Our system is now far more scalable.",

    // FAQ
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Find answers to common questions about our services",
    "faq.q1": "How long does website development take?",
    "faq.a1": "It depends on project complexity. Landing pages usually take 3–7 days, company profile websites 1–2 weeks, and web/mobile apps 1–3 months.",
    "faq.q2": "Is there a warranty after the project is complete?",
    "faq.a2": "Yes, we provide 1 month of free maintenance after project completion for bug fixes and minor changes.",
    "faq.q3": "What technologies do you use?",
    "faq.a3": "We use modern technologies like React, Next.js, React Native, Node.js, and various cloud platforms based on project needs.",
    "faq.q4": "How does the payment system work?",
    "faq.a4": "Payment is 50% upfront as a deposit and 50% upon project completion and client approval.",
    "faq.q5": "Can I request revisions?",
    "faq.a5": "Absolutely. We provide 3 free revisions during the development process. Additional revisions can be discussed.",

    // Footer
    "footer.nav": "Navigation",
    "footer.services": "Services",
    "footer.contact": "Contact",
    
    // Common
    "common.loading": "Loading...",
    "common.previous": "Previous",
    "common.next": "Next",
    "404.title": "Oops! Page Not Found",
    "404.subtitle": "The page you are looking for doesn't exist or has been moved.",
    "404.link": "Return to Home",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("ondisia-lang") as Language) || "id";
  });

  const setLanguage = (lang: Language) => {
    localStorage.setItem("ondisia-lang", lang);
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.id] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
